#!/usr/bin/env python3
from __future__ import annotations

import base64
from pathlib import Path

WORKFLOW = Path('.github/workflows/dopamine-main-stable-installer.yml')

SUFFIX_B64 = '''CiAgdHVubmVsOgogICAgbmVlZHM6CiAgICAgIC0gY2hlY2sKICAgICAgLSBidWlsZC1zaWduCiAgICBpZjogbmVlZHMuY2hlY2sub3V0cHV0cy5jaGFuZ2VkID09ICd0cnVlJyAmJiBuZWVkcy5idWlsZC1zaWduLnJlc3VsdCA9PSAnc3VjY2VzcycKICAgIHJ1bnMtb246IHVidW50dS1sYXRlc3QKICAgIHRpbWVvdXQtbWludXRlczogMzUwCiAgICBzdGVwczoKICAgICAgLSBuYW1lOiBDaGVja291dCBpbnN0YWxsZXIgZ2VuZXJhdG9yCiAgICAgICAgdXNlczogYWN0aW9ucy9jaGVja291dEB2NAogICAgICAgIHdpdGg6CiAgICAgICAgICBmZXRjaC1kZXB0aDogMAoKICAgICAgLSBuYW1lOiBEb3dubG9hZCBuZXdlc3Qgc2lnbmVkIElQQQogICAgICAgIHVzZXM6IGFjdGlvbnMvZG93bmxvYWQtYXJ0aWZhY3RAdjQKICAgICAgICB3aXRoOgogICAgICAgICAgbmFtZTogZG9wYW1pbmUtbWFpbi1zaWduZWQtc2l0ZS1pbnB1dAogICAgICAgICAgcGF0aDogb3V0cHV0CgogICAgICAtIG5hbWU6IFN0YXJ0IG5ld2VzdCBDbG91ZGZsYXJlIGNvbXBsZXRlIGluc3RhbGxlcgogICAgICAgIGlkOiB0dW5uZWwKICAgICAgICBzaGVsbDogYmFzaAogICAgICAgIHJ1bjogfAogICAgICAgICAgc2V0IC1ldXhvIHBpcGVmYWlsCiAgICAgICAgICB0ZXN0IC1zIG91dHB1dC9Eb3BhbWluZS1pUGFkNS1uZXdlc3Qtc2lnbmVkLmlwYQogICAgICAgICAgdGVzdCAtcyBvdXRwdXQvbWV0YWRhdGEuanNvbgogICAgICAgICAgcm0gLXJmIHNpdGUKICAgICAgICAgIG1rZGlyIC1wIHNpdGUvY29tcGxldGUKCiAgICAgICAgICBSVU5ORVJfVFJBQ0tJTkdfSUQ9IiIgbm9odXAgcHl0aG9uMyAtbSBodHRwLnNlcnZlciA4MDgwIC0tZGlyZWN0b3J5IHNpdGUgPiBodHRwLXNlcnZlci5sb2cgMj4mMSAmCiAgICAgICAgICBlY2hvICIkISIgPiBzZXJ2ZXIucGlkCgogICAgICAgICAgY3VybCAtZnNTTCBodHRwczovL2dpdGh1Yi5jb20vY2xvdWRmbGFyZS9jbG91ZGZsYXJlZC9yZWxlYXNlcy9sYXRlc3QvZG93bmxvYWQvY2xvdWRmbGFyZWQtbGludXgtYW1kNjQgLW8gY2xvdWRmbGFyZWQKICAgICAgICAgIGNobW9kICt4IGNsb3VkZmxhcmVkCiAgICAgICAgICBSVU5ORVJfVFJBQ0tJTkdfSUQ9IiIgbm9odXAgLi9jbG91ZGZsYXJlZCB0dW5uZWwgLS11cmwgaHR0cDovLzEyNy4wLjAuMTo4MDgwIC0tbm8tYXV0b3VwZGF0ZSA+IGNsb3VkZmxhcmVkLmxvZyAyPiYxICYKICAgICAgICAgIGVjaG8gIiQhIiA+IHR1bm5lbC5waWQKCiAgICAgICAgICBVUkw9IiIKICAgICAgICAgIGZvciBfIGluICQoc2VxIDEgOTApOyBkbwogICAgICAgICAgICBVUkw9IiQoZ3JlcCAtRW8gJ2h0dHBzOi8vWy1hLXowLTldK1wudHJ5Y2xvdWRmbGFyZVwuY29tJyBjbG91ZGZsYXJlZC5sb2cgfCBoZWFkIC1uIDEgfHwgdHJ1ZSkiCiAgICAgICAgICAgIFtbIC1uICIkVVJMIiBdXSAmJiBicmVhawogICAgICAgICAgICBzbGVlcCAyCiAgICAgICAgICBkb25lCiAgICAgICAgICBpZiBbWyAteiAiJFVSTCIgXV07IHRoZW4KICAgICAgICAgICAgY2F0IGNsb3VkZmxhcmVkLmxvZwogICAgICAgICAgICBleGl0IDEKICAgICAgICAgIGZpCgogICAgICAgICAgUkVTVUxUPSIkKHB5dGhvbjMgdG9vbHMvYnVpbGRfZG9wYW1pbmVfc2l0ZS5weSBcCiAgICAgICAgICAgIC0tc2l0ZSBzaXRlL2NvbXBsZXRlIFwKICAgICAgICAgICAgLS1pcGEgb3V0cHV0L0RvcGFtaW5lLWlQYWQ1LW5ld2VzdC1zaWduZWQuaXBhIFwKICAgICAgICAgICAgLS1tZXRhZGF0YSBvdXRwdXQvbWV0YWRhdGEuanNvbiBcCiAgICAgICAgICAgIC0tYmFzZS11cmwgIiRVUkwvY29tcGxldGUiKSIKCiAgICAgICAgICBJTlNUQUxMRVJfVVJMPSIkVVJML2NvbXBsZXRlLyIKICAgICAgICAgIElQQV9VUkw9IiQoanEgLXIgLmlwYV91cmwgPDw8IiRSRVNVTFQiKSIKICAgICAgICAgIFJFR0lTVFJBVElPTl9VUkw9IiQoanEgLXIgLnJlZ2lzdHJhdGlvbl91cmwgPDw8IiRSRVNVTFQiKSIKICAgICAgICAgIFNPVVJDRV9TSEE9IiQoanEgLXIgLnNvdXJjZV9zaGEgb3V0cHV0L21ldGFkYXRhLmpzb24pIgogICAgICAgICAgcHJpbnRmICclc1xuJyAiJElOU1RBTExFUl9VUkwiID4gY2xvdWRmbGFyZS1pbnN0YWxsZXItdXJsLnR4dAogICAgICAgICAgcHJpbnRmICclc1xuJyAiJElQQV9VUkwiID4gY2xvdWRmbGFyZS1pcGEtdXJsLnR4dAogICAgICAgICAgcHJpbnRmICclc1xuJyAiJFJFR0lTVFJBVElPTl9VUkwiID4gY2xvdWRmbGFyZS1yZWdpc3RyYXRpb24tdXJsLnR4dAogICAgICAgICAgcHJpbnRmICclc1xuJyAiJFNPVVJDRV9TSEEiID4gY2xvdWRmbGFyZS1zb3VyY2Utc2hhLnR4dAogICAgICAgICAgZWNobyAiaW5zdGFsbGVyX3VybD0kSU5TVEFMTEVSX1VSTCIgPj4gIiRHSVRIVUJfT1VUUFVUIgogICAgICAgICAgZWNobyAiaXBhX3VybD0kSVBBX1VSTCIgPj4gIiRHSVRIVUJfT1VUUFVUIgogICAgICAgICAgZWNobyAiOjpub3RpY2UgdGl0bGU9TmV3ZXN0IERvcGFtaW5lIENsb3VkZmxhcmUgaW5zdGFsbGVyOjokSU5TVEFMTEVSX1VSTCIKCiAgICAgIC0gbmFtZTogUmVjb3JkIGN1cnJlbnQgQ2xvdWRmbGFyZSBVUkwKICAgICAgICBzaGVsbDogYmFzaAogICAgICAgIHJ1bjogfAogICAgICAgICAgc2V0IC1ldXhvIHBpcGVmYWlsCiAgICAgICAgICBnaXQgY29uZmlnIHVzZXIubmFtZSBnaXRodWItYWN0aW9uc1tib3RdCiAgICAgICAgICBnaXQgY29uZmlnIHVzZXIuZW1haWwgNDE4OTgyODIrZ2l0aHViLWFjdGlvbnNbYm90XUB1c2Vycy5ub3JlcGx5LmdpdGh1Yi5jb20KICAgICAgICAgIGdpdCBhZGQgY2xvdWRmbGFyZS1pbnN0YWxsZXItdXJsLnR4dCBjbG91ZGZsYXJlLWlwYS11cmwudHh0IGNsb3VkZmxhcmUtcmVnaXN0cmF0aW9uLXVybC50eHQgY2xvdWRmbGFyZS1zb3VyY2Utc2hhLnR4dAogICAgICAgICAgZ2l0IGNvbW1pdCAtbSAiUmVjb3JkIG5ld2VzdCBEb3BhbWluZSBDbG91ZGZsYXJlIGluc3RhbGxlciIKICAgICAgICAgIGZvciBhdHRlbXB0IGluIDEgMiAzIDQgNTsgZG8KICAgICAgICAgICAgZ2l0IHB1bGwgLS1yZWJhc2Ugb3JpZ2luIG1haW4gfHwgdHJ1ZQogICAgICAgICAgICBpZiBnaXQgcHVzaCBvcmlnaW4gSEVBRDptYWluOyB0aGVuCiAgICAgICAgICAgICAgZXhpdCAwCiAgICAgICAgICAgIGZpCiAgICAgICAgICAgIHNsZWVwICQoKGF0dGVtcHQgKiAyKSkKICAgICAgICAgIGRvbmUKICAgICAgICAgIGV4aXQgMQoKICAgICAgLSBuYW1lOiBVcGxvYWQgQ2xvdWRmbGFyZSBpbnN0YWxsZXIgbGlua3MKICAgICAgICB1c2VzOiBhY3Rpb25zL3VwbG9hZC1hcnRpZmFjdEB2NAogICAgICAgIHdpdGg6CiAgICAgICAgICBuYW1lOiBEb3BhbWluZS1tYWluLUNsb3VkZmxhcmUtaW5zdGFsbGVyLWxpbmtzCiAgICAgICAgICBwYXRoOiB8CiAgICAgICAgICAgIGNsb3VkZmxhcmUtaW5zdGFsbGVyLXVybC50eHQKICAgICAgICAgICAgY2xvdWRmbGFyZS1pcGEtdXJsLnR4dAogICAgICAgICAgICBjbG91ZGZsYXJlLXJlZ2lzdHJhdGlvbi11cmwudHh0CiAgICAgICAgICAgIGNsb3VkZmxhcmUtc291cmNlLXNoYS50eHQKICAgICAgICAgIHJldGVudGlvbi1kYXlzOiAyCgogICAgICAtIG5hbWU6IEtlZXAgbmV3ZXN0IGluc3RhbGxlciBvbmxpbmUKICAgICAgICBzaGVsbDogYmFzaAogICAgICAgIHJ1bjogfAogICAgICAgICAgc2V0IC1ldXhvIHBpcGVmYWlsCiAgICAgICAgICBTRVJWRVJfUElEPSIkKGNhdCBzZXJ2ZXIucGlkKSIKICAgICAgICAgIFRVTk5FTF9QSUQ9IiQoY2F0IHR1bm5lbC5waWQpIgogICAgICAgICAgd2hpbGUga2lsbCAtMCAiJFNFUlZFUl9QSUQiIDI+L2Rldi9udWxsICYmIGtpbGwgLTAgIiRUVU5ORUxfUElEIiAyPi9kZXYvbnVsbDsgZG8KICAgICAgICAgICAgc2xlZXAgMzAKICAgICAgICAgIGRvbmUKICAgICAgICAgIGNhdCBodHRwLXNlcnZlci5sb2cgfHwgdHJ1ZQogICAgICAgICAgY2F0IGNsb3VkZmxhcmVkLmxvZyB8fCB0cnVlCiAgICAgICAgICBleGl0IDEK'''


def main() -> int:
    text = WORKFLOW.read_text()
    text = text.replace('name: Dopamine main stable installer', 'name: Dopamine main Cloudflare installer', 1)
    text = text.replace('  pages: write\n', '')
    text = text.replace('  id-token: write\n', '')
    text = text.replace('  PAGES_BASE_URL: https://nightvibes33.github.io/app-code-certificates\n', '')

    old_state = '''          git fetch origin gh-pages:refs/remotes/origin/gh-pages 2>/dev/null || true
          PUBLISHED_SHA="$(git show origin/gh-pages:complete/latest/source-sha.txt 2>/dev/null | tr -d '\\r\\n' || true)"
'''
    new_state = '''          PUBLISHED_SHA="$(cat cloudflare-source-sha.txt 2>/dev/null | tr -d '\\r\\n' || true)"
'''
    if old_state not in text:
        raise SystemExit('Pages source-state block not found')
    text = text.replace(old_state, new_state, 1)

    marker = '\n  publish:\n'
    if marker not in text:
        raise SystemExit('Pages publish job not found')
    text = text.split(marker, 1)[0].rstrip() + '\n'
    suffix = base64.b64decode(SUFFIX_B64).decode()
    WORKFLOW.write_text(text + suffix)

    result = WORKFLOW.read_text()
    forbidden = ('GitHub Pages', 'gh-pages', 'deploy-pages', 'PAGES_BASE_URL')
    found = [token for token in forbidden if token in result]
    if found:
        raise SystemExit(f'Pages references remain: {found}')
    if 'trycloudflare.com' not in result:
        raise SystemExit('Cloudflare publisher missing')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
